package formatter.streamconverter;

public enum StackMarker {
    NAMESPACE_DECL,
    NAMESPACE_LEFT_BRACE,
    NAMESPACE_RIGHT_BRACE,

    // CLASS,
    DO_WHILE_DO,
    DO_WHILE_LFT_BR,
    DO_WHILE_RHT_BR,
    DO_WHILE_WHILE,
    DO_WHILE_PARENTH_LEFT,
    DO_WHILE_PARENTH_RIGHT,

    WHILE,
    WHILE_LEFT_PARENTH,
    WHILE_RIGHT_PARENTH,
    WHILE_LEFT_BRACE,
    WHILE_RIGHT_BRACE,

    IF,
    IF_LEFT_BRACE,
    IF_RIGHT_BRACE,
    IF_PARENTH_LEFT,
    IF_PARENTH_RIGHT,

    ELSE,
    ELSE_LEFT_BRACE,
    ELSE_RIGHT_BRACE,

    FOR,
    FOR_LEFT_BRACE,
    FOR_RIGHT_BACE,
    FOR_LEFT_PARENTH,
    FOR_RIGHT_PARENTH,
    FOR_FIRST_SEMICOLON,
    FOR_SECOND_SEMICOLON,
    FOR_SEMICOLON,

    SWITCH,
    SWITCH_LEFT_PARENTH,
    SWITCH_RIGHT_PARENTH,
    SWITCH_LEFT_BRACE,
    SWITCH_RIGTHT_BRACE,

    CASE,

    TRY,
    TRY_LEFT_BRACE,
    TRY_RIGHT_BRACE,

    CATCH,
    CATCH_LEFT_PARENTH,
    CATCH_RIGHT_PARENTH,
    CATCH_LEFT_BRACE,
    CATCH_RIGHT_BRACE,

    TERNARY_OP,

    CLASS_DECL,
    CLASS_NAME_DECL,

    STRUCTURE_DECL,
    STRUCTURE_NAME_DECL,

    BASE_COLON,

    TEMPLATE_DECL,
    TEMPLATE_LEFT_ANGLE_BRACKET,
    TEMPLATE_RIGHT_ANGLE_BRACKET,

    CAPTURE_LIST_LEFT_BRACKET,
    CAPTURE_LIST_RIGHT_BRACKET,
    LAMBDA_DECL_LEFT_PARENTH,
    LAMBDA_DECL_RIGHT_PARENTH,

    ARRAY_LEFT_BRACKET,
    ARRAY_RIGHT_BRACKET,

    TYPENAME_DECL,
    TYPENAME_NAME_DECL,
    CLASS_IN_TEMPLATE_DECL,
    CLASS_IN_TEMPLATE_DECL_NAME,
    CLASS_DEF_LEFT_BRACE,
    CLASS_DEF_RIGHT_BRACE,

    FUNCTION_DECL_ARG_LEFT_PARENTH,
    FUNCTION_DECL_ARG_RIGHT_PARENTH,
    FUNCTION_DECL_LEFT_BRACE,
    FUNCTION_DECL_RIGHT_BRACE,

    ID_MAYBE_DECL,


    STACK_FIRST_MARKER
}
